site_name: Portfolio

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: purple



  language : fr
  features : 
    - navigation.footer

nav :
  - Accueil : index.md
  - Profil : profil.md
  - Compétences :
    - Liste des compétences : compétences/compétences.md 
    - Gestion du patrimoine informatique : compétences/patrimoine-informatique.md
    - Support et assistance : compétences/support-assistance.md
    - Développement de la prénsence en ligne d'une organisation : compétences/présence-en-ligne.md
    - Travail en mode projet : compétences/travail-mode-projet.md
    - Déploiement d'un service informatique à des utilisateurs : compétences/déploiement-service-info.md
    - Développement professionnel : compétences/développement-professionel.md

extra : 
  generator : false
  social : 
    - icon : fontawesome/solid/paper-plane
      link: mailto:<arthur.richert.villain@gmail.com>
    - icon : fontawesome/brands/github
      link : https://github.com/saulevant
    - icon : fontawesome/brands/linkedin
      link : https://fr.linkedin.com/in/arthur-richert-villain-a87312346
